version: "3.1"
services:
  mysql:
    container_name: mysql
    ports:
      - "3306:3306"
    image: mysql:latest
    networks:
      - mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql-network

networks:
  mysql-network:
volumes:
  mysql-data:
